// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mg1_edit_writer_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg1_edit_writer_image));
        
        string IMigrationMetadata.Id
        {
            get { return "202107121556076_mg1_edit_writer_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
